/**
 * Dockerfile Generator
 * Auto-generates Dockerfiles based on detected runtime
 */

import type { DeployConfig } from "../types";

/**
 * Normalize start command for Docker deployment.
 * Adds --host flags for dev servers that default to localhost binding.
 */
function normalizeStartCommandForDocker(startCommand: string): string {
    const cmd = startCommand.trim();

    // Vite: needs --host flag
    // Matches: vite, vite dev, vite serve, npx vite, npm run dev (when it's vite)
    if (/\bvite\b/.test(cmd) && !cmd.includes('--host')) {
        return cmd + ' --host';
    }

    // Next.js dev: needs -H 0.0.0.0
    // Matches: next dev, npx next dev
    if (/\bnext\s+dev\b/.test(cmd) && !cmd.includes('-H ') && !cmd.includes('--hostname')) {
        return cmd + ' -H 0.0.0.0';
    }

    // Webpack Dev Server: needs --host 0.0.0.0
    if (/\bwebpack\s+serve\b/.test(cmd) && !cmd.includes('--host')) {
        return cmd + ' --host 0.0.0.0';
    }

    // Angular CLI (ng serve): needs --host 0.0.0.0
    if (/\bng\s+serve\b/.test(cmd) && !cmd.includes('--host')) {
        return cmd + ' --host 0.0.0.0';
    }

    // Nuxt dev: needs --host
    if (/\bnuxt\s+dev\b/.test(cmd) && !cmd.includes('--host') && !cmd.includes('-H')) {
        return cmd + ' --host';
    }

    // Astro dev: needs --host
    if (/\bastro\s+dev\b/.test(cmd) && !cmd.includes('--host')) {
        return cmd + ' --host';
    }

    // SvelteKit dev (vite-based, already covered by vite check above)

    return cmd;
}

/**
 * Generate a Dockerfile based on the deployment config
 */
export function generateDockerfile(config: DeployConfig): string {
    const runtime = config.runtime || 'node';  // Default to node if not specified

    switch (runtime.toLowerCase()) {
        case 'node':
            return generateNodeDockerfile(config);
        case 'python':
            return generatePythonDockerfile(config);
        case 'go':
            return generateGoDockerfile(config);
        case 'bun':
            return generateBunDockerfile(config);
        case 'deno':
            return generateDenoDockerfile(config);
        default:
            throw new Error(`Unsupported runtime: ${runtime}`);
    }
}

/**
 * Generate Dockerfile for Node.js applications
 */
function generateNodeDockerfile(config: DeployConfig): string {
    return `# Auto-generated by okastr8
FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --production

# Copy application code
COPY . .

# Run build steps if any
${config.buildSteps.length > 0 ? `RUN ${config.buildSteps.join(' && ')}` : '# No build steps'}

# Expose port
EXPOSE ${config.port}

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget --spider -q http://localhost:${config.port}/health || exit 1

# Start application
CMD ${JSON.stringify(normalizeStartCommandForDocker(config.startCommand).split(' '))}
`;
}

/**
 * Generate Dockerfile for Python applications
 */
function generatePythonDockerfile(config: DeployConfig): string {
    return `# Auto-generated by okastr8
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Run build steps if any
${config.buildSteps.length > 0 ? `RUN ${config.buildSteps.join(' && ')}` : '# No build steps'}

# Expose port
EXPOSE ${config.port}

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD curl -f http://localhost:${config.port}/health || exit 1

# Start application
CMD ${JSON.stringify(normalizeStartCommandForDocker(config.startCommand).split(' '))}
`;
}

/**
 * Generate Dockerfile for Go applications
 */
function generateGoDockerfile(config: DeployConfig): string {
    return `# Auto-generated by okastr8
# Build stage
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN go build -o main .

# Runtime stage
FROM alpine:latest

WORKDIR /app

# Install ca-certificates for HTTPS
RUN apk --no-cache add ca-certificates wget

# Copy binary from builder
COPY --from=builder /app/main .

# Expose port
EXPOSE ${config.port}

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget --spider -q http://localhost:${config.port}/health || exit 1

# Start application
CMD ["./main"]
`;
}

/**
 * Generate Dockerfile for Bun applications
 */
function generateBunDockerfile(config: DeployConfig): string {
    return `# Auto-generated by okastr8
FROM oven/bun:1-alpine

WORKDIR /app

# Install dependencies
COPY package.json bun.lockb ./
RUN bun install --production

# Copy application code
COPY . .

# Run build steps if any
${config.buildSteps.length > 0 ? `RUN ${config.buildSteps.join(' && ')}` : '# No build steps'}

# Expose port
EXPOSE ${config.port}

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget --spider -q http://localhost:${config.port}/health || exit 1

# Start application
CMD ${JSON.stringify(normalizeStartCommandForDocker(config.startCommand).split(' '))}
`;
}

/**
 * Generate Dockerfile for Deno applications
 */
function generateDenoDockerfile(config: DeployConfig): string {
    return `# Auto-generated by okastr8
FROM denoland/deno:alpine

WORKDIR /app

# Cache dependencies
COPY deno.json deno.lock ./
RUN deno cache deno.json

# Copy application code
COPY . .

# Expose port
EXPOSE ${config.port}

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget --spider -q http://localhost:${config.port}/health || exit 1

# Start application
CMD ${JSON.stringify(normalizeStartCommandForDocker(config.startCommand).split(' '))}
`;
}
