import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  users: defineTable({
    githubUserId: v.number(),
    githubUsername: v.string(),
    githubAccessToken: v.optional(v.string()), // Optional, could be stored in a separate table for security
  }).index("by_github_user_id", ["githubUserId"]),

  servers: defineTable({
    userId: v.id("users"),
    serverId: v.string(), // UUID generated by the CLI
    serverToken: v.string(), // Hashed token for WebSocket auth
    name: v.optional(v.string()),
  }).index("by_server_id", ["serverId"]).index("by_user_id", ["userId"]),

  installations: defineTable({
    userId: v.id("users"),
    githubInstallationId: v.number(),
  }).index("by_user_id", ["userId"]).index("by_github_installation_id", ["githubInstallationId"]),

  deviceCodes: defineTable({
    code: v.string(),
    userCode: v.string(), // The short code shown to the user (e.g. ABCD-1234)
    status: v.union(v.literal("pending"), v.literal("authorized"), v.literal("expired"), v.literal("consumed")),
    userId: v.optional(v.id("users")),
    serverId: v.string(),
    expiresAt: v.number(),
  }).index("by_user_code", ["userCode"]).index("by_code", ["code"]),
});
